yarn add --dev @babel/plugin-syntax-dynamic-import
- Commit a7fd832cbdc8cb1dfc4edfe521beb9404f40fdbc executed `yarn upgrade`.
- Since that upgrade, errors are encountered when executing `rails assets:precompile` (see below) These changes resolves the error.
```
$ DISABLE_SPRING=1 rails assets:precompile
Copying Bootstrap glyphicons to the public directory ...
Copying TinyMCE skins to the public directory ...
yarn install v1.22.22
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.16s.
yarn run v1.22.22
$ webpack --config ./config/webpack/webpack.config.js
assets by status 4.71 KiB [cached] 1 asset
./app/javascript/application.js 39 bytes [built] [code generated] [1 error]

ERROR in ./app/javascript/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find package '@babel/plugin-syntax-dynamic-import' imported from /home/aaron/Documents/GitHub/roadmap_upstream/babel-virtual-resolve-base.js
    at new NodeError (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:195:5)
    at packageResolve (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:899:9)
    at moduleResolve (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:939:18)
    at defaultResolve (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1017:15)
    at resolve (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1030:12)
    at tryImportMetaResolve (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/files/plugins.js:149:45)
    at resolveStandardizedNameForImport (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/files/plugins.js:174:19)
    at resolveStandardizedName (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/files/plugins.js:186:22)
    at loadPlugin (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/files/plugins.js:56:7)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/config-descriptors.js:140:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/gensync/index.js:291:5)
    at /home/aaron/Documents/GitHub/roadmap_upstream/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/gensync/index.js:43:15)
    at Function.all (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/config-descriptors.js:102:41)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
    at createPluginDescriptors.next (<anonymous>)
    at /home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/gensync-utils/functional.js:39:27
    at Generator.next (<anonymous>)
    at mergeChainOpts (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/config-chain.js:349:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/config-chain.js:316:14)
    at chainWalker.next (<anonymous>)
    at loadFileChain (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/config-chain.js:191:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/config-chain.js:77:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/partial.js:72:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadPartialConfig (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/partial.js:115:25)
    at loadPartialConfig.next (<anonymous>)
    at step (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/gensync/index.js:269:25)
    at evaluateAsync (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/gensync/index.js:291:5)
    at /home/aaron/Documents/GitHub/roadmap_upstream/node_modules/gensync/index.js:93:9
    at new Promise (<anonymous>)
    at async (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/gensync/index.js:92:14)
    at stopHiding - secret - don't use this - v1 (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at Object.loadPartialConfigAsync (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/@babel/core/lib/config/index.js:34:85)
    at Object.loader (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/babel-loader/lib/index.js:116:30)
    at Object.<anonymous> (/home/aaron/Documents/GitHub/roadmap_upstream/node_modules/babel-loader/lib/index.js:39:12)

webpack 5.98.0 compiled with 1 error in 259 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
bin/rails aborted!
jsbundling-rails: Command build failed, ensure `yarn build` runs without errors

Tasks: TOP => assets:precompile => javascript:build
(See full trace by running task with --trace)
```