Replace deprecated `setup-ruby` action
The following error was being encountered in https://github.com/DMPRoadmap/roadmap/actions/runs/13907418160/job/38913596385?pr=3487:

```
Run actions/setup-ruby@v1
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 3.0.4 not found
```